### ISSUE TITLE
Adjust path/ import of config in transfer results module

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#25]
When running the transfer of the results from firebase to a mysql instance the following error occurs:
```
Unable to load configuration file at ./cfg/config.cfg. Exiting.
Traceback (most recent call last):
  File "transfer_results.py", line 12, in <module>
    from cfg.auth import firebase_admin_auth
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/data/environments/mapswipe_workers/lib/python3.4/site-packages/mapswipe_workers-0.0.1-py3.4.egg/cfg/auth.py", line 14, in <module>
FileNotFoundError: [Errno 2] No such file or directory: './cfg/config.cfg'
```

The same errors occurs for the import module, export module and the update module.

**Comment by Hagellach37** [comment]
ahh okay, so I got that:
we need to run the script from the main directory. However, we still get an error:
```
FileNotFoundError processing TIN / NPI message! In <module>, the following error happened - 2 at line 235. 
no slack token provided
```

**Comment by Hagellach37** [comment]
this relates to the following:
```
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '../cfg/yourServiceAccount.json'
```
So we just need to make sure to pass the correct path to the service account file within our config file.

**Comment by Hagellach37** [comment]
So let's close this. The code works, the only thing we need to be careful about is our `config.cfg` file however we need add something to our error handling to get down to such issues more quickly. I will open an issue for this. :)
