### ISSUE TITLE
Create Projects: AttributeError: 'NoneType' object has no attribute 'CreateDataSource'

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#363]
During test of project creation following error occurs:

```
Traceback (most recent call last):
  File "mapswipe/python-mapswipe-workers/mapswipe_workers/mapswipe_workers/project_types/base/project.py", line 136, in save_project
    self.save_to_files(project)
  File "mapswipe/python-mapswipe-workers/mapswipe_workers/mapswipe_workers/project_types/base/project.py", line 392, in save_to_files
    geojson_functions.create_geojson_file(geometries, outfile)
  File "mapswipe/python-mapswipe-workers/mapswipe_workers/mapswipe_workers/utils/geojson_functions.py", line 244, in create_geojson_file
    dataSource = driver.CreateDataSource(outfile_temp)
AttributeError: 'NoneType' object has no attribute 'CreateDataSource'
2020-05-24 11:28:12,807 - INFO - project.py - save_project - test_build_area deleted project data from files and postgres
Traceback (most recent call last):
  File "mapswipe/python-mapswipe-workers/mapswipe_workers/mapswipe_workers/project_types/base/project.py", line 136, in save_project
    self.save_to_files(project)
  File "mapswipe/python-mapswipe-workers/mapswipe_workers/mapswipe_workers/project_types/base/project.py", line 392, in save_to_files
    geojson_functions.create_geojson_file(geometries, outfile)
  File "mapswipe/python-mapswipe-workers/mapswipe_workers/mapswipe_workers/utils/geojson_functions.py", line 244, in create_geojson_file
    dataSource = driver.CreateDataSource(outfile_temp)
AttributeError: 'NoneType' object has no attribute 'CreateDataSource'
```

**Comment by Hagellach37** [comment]
relates to #421

**Comment by Hagellach37** [comment]
#438
