### ISSUE TITLE
Test fail due to late Firebase Function completion.

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#416]
```
======================================================================
FAIL: test_changes (test_archive_project.TestArchiveProject)
Test if groups, tasks and results are deleted from Firebase.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tests/integration/test_archive_project.py", line 28, in test_changes
    self.assertIsNone(ref.get())
AssertionError: {'g115': {'progress': 33}} is not None
```

**Comment by Matthias-Schaub** [comment]
Wait for Firebase Functions to complete during test setup.

**Comment by Matthias-Schaub** [comment]
Sometimes all tests are executed successful sometimes not:

```
======================================================================
FAIL: test_changes (test_archive_project.TestArchiveProject)
Test if groups, tasks and results are deleted from Firebase.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tests/integration/test_archive_project.py", line 25, in test_changes
    self.assertIsNone(ref.get())
AssertionError: {'g115': {'progress': 33}} is not None
```

**Comment by Matthias-Schaub** [comment]
Waiting for 4 seconds after the archive function is called before testing firebase changes fixes this issue.

**Comment by Hagellach37** [comment]
seems to be an issue still: https://travis-ci.org/github/mapswipe/python-mapswipe-workers/builds/741922678
