### ISSUE TITLE
Transfer the data from Firebase to Postgres

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#66]
Write a script which transfers the data from the Firebase instance to the Postgres database

**Comment by maze2point0** [comment]
So far we only stored results and users in mysql along with projects but only 3 attributes there.

As the rewritten, now modular python mapswipe workers in addition store all infos on projects as well as now groups and tasks and imports in postgres. We need to import all the respective tables which are in firebase only for now:
- [ ] - imports table
- [ ] - projects table
- [ ] - groups table
- [ ] - tasks table

**Comment by maze2point0** [comment]
users included in the script now as well.

ran into an error related to paths. When I move the script from mapswipe-workers/utils to /
I am able to execute it without any problems

```sh
root@ac4e988aa869:/python-mapswipe-workers# python mapswipe_workers/utils/import_firebase_to_psql.py -op download
/usr/local/lib/python3.6/site-packages/psycopg2-2.7.6.1-py3.6-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "mapswipe_workers/utils/import_firebase_to_psql.py", line 369, in <module>
    firebase, postgres = b.get_environment(args.modus)
  File "/usr/local/lib/python3.6/site-packages/mapswipe_workers-0.0.2-py3.6.egg/mapswipe_workers/basic/BaseFunctions.py", line 49, in get_environment
    firebase = auth.dev_firebase_admin_auth()
  File "/usr/local/lib/python3.6/site-packages/mapswipe_workers-0.0.2-py3.6.egg/mapswipe_workers/basic/auth.py", line 57, in dev_firebase_admin_auth
    CONFIG = load_config()
  File "/usr/local/lib/python3.6/site-packages/mapswipe_workers-0.0.2-py3.6.egg/mapswipe_workers/basic/auth.py", line 23, in load_config
    with open(CONFIG_PATH) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/mapswipe_workers-0.0.2-py3.6.egg/cfg/configuration.json'
```

**Comment by maze2point0** [comment]
I added a report script which checks for consistency between firebase and postgres.
303cff94cbb8e777a503024226b114b5683d2e7e
