### ISSUE TITLE
Import process - in case of duplicate key constrain do not delete in firebase and postgres

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#78]
In case of already exsisting key in Postgres during Import process (firebaseProjectId = postgresProjectId) do not delete the Project in Firebase and Postgres. Instead raise and log an custom error. Make sure nothing changed during import of this project and import of other projects continues.

**Comment by Matthias-Schaub** [comment]
```
WARNING:root:-LYS6Y_qVEz8ne5KjpRL - import_project - could not import project
WARNING:root:-LYS6Y_qVEz8ne5KjpRL - import_project - duplicate key value violates unique constraint "projects_pkey"
DETAIL:  Key (project_id)=(1006) already exists.

ERROR:root:Error detail:
Traceback (most recent call last):

  File "/home/matthias/Arbeit/projekte/python-mapswipe-workers/mapswipe_workers/basic/BaseImport.py", line 113, in create_project
    self.set_project_postgres(postgres, project_dict)

  File "/home/matthias/Arbeit/projekte/python-mapswipe-workers/mapswipe_workers/basic/BaseImport.py", line 242, in set_project_postgres
    p_con.query(sql_insert, data)

  File "/home/matthias/Arbeit/projekte/python-mapswipe-workers/mapswipe_workers/basic/auth.py", line 277, in query
    self._db_cur.execute(query, data)

psycopg2.IntegrityError: duplicate key value violates unique constraint "projects_pkey"
DETAIL:  Key (project_id)=(1006) already exists.



WARNING:root:1006 - delete_results_postgres - deleted all results, tasks, groups and import and project in postgres
WARNING:root:1006 - delete_project_firebase - deleted project and groups and import in firebase
WARNING:root:1006 - delete_project_firebase - deleted local files:
```

**Comment by Matthias-Schaub** [comment]
All import related sql-queries are now handled as a single transaction.
